### ISSUE TITLE
Files are corrupted

### ISSUE THREAD

**Issue by Eshan-Agarwal** [armancohan/long-summarization#7]
Hey, After downloading files I try to extract them, but got error while extracting `train.txt` it says : `File is corrupted`

**Comment by Conchylicultor** [comment]
It seems other people have the same issue: https://stackoverflow.com/questions/56204755/zipfile-extractall-raising-badzipfile-bad-crc-32-for-file-error

**Comment by Conchylicultor** [comment]
For more context, [this dataset](https://www.tensorflow.org/datasets/catalog/scientific_papers) is available in Tensorflow Datasets but users cannot use it, apparently due to the corrupted `train.txt` files when extracting the original archive file from your website.

Context: https://github.com/tensorflow/datasets/issues/1404

We cannot re-host the data ourselves. Fixing the file would help promote your datasets to the entire Tensorflow community.

**Comment by armancohan** [comment]
I can't replicate this issue. What tool are you using to unzip the file?
I just tried it with Mac's default unzip tool and it works just fine.

**Comment by Eshan-Agarwal** [comment]
I tried `winrar` and `winzip` in `windows` but it shows error that `train.txt` is corrupted as well as this dataset is also available in `Tensorflow` so when trying to load it from their it shows `Bad Crc 32` error which arises due to corrupted `train.txt` file

**Comment by armancohan** [comment]
Ok, I haven't tried it on Windows but was able to replicate the issue using Zipfile when directly reading from python. Will re compress the files and post again. Thanks for reporting the issue.

**Comment by Eshan-Agarwal** [comment]
Thanks for helping.

**Comment by armancohan** [comment]
@Eshan-Agarwal  @Conchylicultor 
I recompressed the data and uploaded the new files. Please check out the new links on the Readme and let me know if you still have issues.

**Comment by Eshan-Agarwal** [comment]
@armancohan  Thanks for updating files, it works fine now.
